apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: flyte
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 25Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: flyte
  labels:
    app.kubernetes.io/name: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: minio
  template:
    metadata:
      labels:
        app.kubernetes.io/name: minio
    spec:
      containers:
        - image: "bitnami/minio:2024.4.18"
          imagePullPolicy: "IfNotPresent"
          name: minio
          env:
            - name: MINIO_ROOT_USER
              value: minio123
            - name: MINIO_ROOT_PASSWORD
              value: minio123  # 8 character long
            - name: MINIO_DEFAULT_BUCKETS
              value: flyte
          ports:
            - containerPort: 9000
              name: minio
            - containerPort: 9001
              name: minio-console
          resources:
            limits:
              cpu: 250m
              memory: 512Mi
            requests:
              cpu: 50m
              memory: 128Mi
          volumeMounts:
            - name: minio-storage
              mountPath: /data
      volumes:
        - name: minio-storage
          persistentVolumeClaim:
            claimName: minio-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: flyte
  labels:
    app.kubernetes.io/name: minio
spec:
  type: NodePort
  ports:
    - name: minio
      nodePort: 30084
      port: 9000
      protocol: TCP
      targetPort: minio
    - name: minio-console
      nodePort: 30088
      port: 9001
      protocol: TCP
      targetPort: minio-console
  selector:
    app.kubernetes.io/name: minio
