configuration:
  database:
    username: postgres
    password: postgres
    host: postgres-postgresql.flyte.svc.cluster.local
    dbname: postgres
    port: 5432
    options: sslmode=disable
  storage:
    type: minio
    metadataContainer: metadata #This is the default bucket created with Minio. Controlled by the MINIO_DEFAULT_BUCKETS env var in the local-flyte-resources.yaml manifest
    userDataContainer: data
    provider: s3
    providerConfig:
      s3:
        authType: "accesskey"
#        endpoint: "http://minio.flyte.svc.cluster.local:9000"
        endpoint: "http://10.96.132.61"
        accessKey: "admin123"
        secretKey: "admin123" #If you need to change this parameters, refer to the local-flyte-resources.yaml manifest and adjust the MINIO_ROOT_PASSWORD env var
        disableSSL: "true"
        secure: "false"
        v2Signing: "true"
deployment:
  waitForDB:
    image:
      repository: postgres
      tag: 15-alpine
      pullPolicy: IfNotPresent
    command: [ ]
    args: [ ]

#  inlineSecretRef: flyte-binary-inline-config-secret
#  inline:
#    plugins:
#      k8s:
#        inject-finalizer: true
#        default-env-vars:
#          - FLYTE_AWS_ENDPOINT: "http://minio.flyte.svc.cluster.local:9000"
#          - FLYTE_AWS_ACCESS_KEY_ID: "minio"
#          - FLYTE_AWS_SECRET_ACCESS_KEY: "miniostorage" #Use the same value as the MINIO_ROOT_PASSWORD

#    task_resources:
#      defaults:
#        cpu: 100m
#        memory: 500Mi #change default requested resources and limits to fit your needs
#      limits:
#        memory: 2Gi

serviceAccount:
  create: true


